apiVersion: v1
kind: Service
metadata:
  labels:
    app: py-app
  name: py-app-svc
spec:
  type: NodePort
  selector:
    app: py-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
