apiVersion: v1
kind: Service
metadata:
  labels:
    app: py-app
  name: py-app-svc
spec:
  type: LoadBalancer
  selector:
    app: py-app
  ports:
  - port: 5000
    targetPort: 5000
    #nodePort: 30000
    protocol: TCP
